Fix a dangling pointer discovered by a fresh Clang (#1222) (#1224)
Fix a dangling pointer discovered by the -Wdangling Clang diagnostic:
```
rcl/src/rcl/node_resolve_name.c:95:26: error: temporary whose address is used as value of local variable 'error' will be destroyed at the end of the full-expression [-Werror,-Wdangling]
   95 |     const char * error = rmw_get_error_string().str;
```

Signed-off-by: Alexander Kornienko <alexfh@google.com>
(cherry picked from commit 57dc28e3c396f2a3ce1e2a1b065f298b8fdd49cc)

Co-authored-by: Alexander Kornienko <alexfh@google.com>